version: "3"
services:
  springboot:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/otif
    container_name: spring_otif
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo:4.4.1
    container_name: mongodb_otif
    ports:
      - 27017:27017
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge